/*
Author: Sighfy
Project: PC8_102
PLEASE DO NOT PRINT THIS ENTIRE SOURCE FILE
*/

#include <iostream>
#include <iomanip>
#include <string>

using namespace std;

int Menu();
void DisplayRecord(string city, double rate, string county, bool headings);
void DisplayRecordHeading();
void selectionSort(string SalesTax[][3], int size);
int binarySearch(string salesTax[][3], int size, string city);
int sequentialSearch(string salesTax[][3], int size,
    string county, bool countyFound[]);

int main()
{
    const int ROWS = 1785, FIELDS = 3;
    const bool SHOWHEADINGS = true, NOHEADINGS = false;
    enum CHOICE { CITY = 1, COUNTY, EXIT };
    int index = 0, choice = 0;
    string city, county, rate;
    bool countyFound[ROWS], firstCity;

    string SalesTax[ROWS][FIELDS] = { "Alameda", "9.25", "Alameda",
        "Albany", "9.75", "Alameda",
        "Army Terminal", "9.25", "Alameda",
        "Ashland", "9.25", "Alameda",
        "Berkeley", "9.25", "Alameda",
        "Bradford", "9.25", "Alameda",
        "Castro Valley", "9.25", "Alameda",
        "Cresta Blanca", "9.25", "Alameda",
        "Dublin", "9.25", "Alameda",
        "Elmwood", "9.25", "Alameda",
        "Emeryville", "9.25", "Alameda",
        "Fremont", "9.25", "Alameda",
        "Government Island", "9.25", "Alameda",
        "Hayward", "9.75", "Alameda",
        "Heyer", "9.25", "Alameda",
        "Landscape", "9.25", "Alameda",
        "Livermore", "9.25", "Alameda",
        "Naval Air Station (Alameda)", "9.25", "Alameda",
        "Naval Hospital (Oakland)", "9.25", "Alameda",
        "Naval Supply Center (Oakland)", "9.25", "Alameda",
        "Newark", "9.75", "Alameda",
        "Oakland", "9.25", "Alameda",
        "Piedmont", "9.25", "Alameda",
        "Pleasanton", "9.25", "Alameda",
        "San Leandro", "9.75", "Alameda",
        "San Lorenzo", "9.25", "Alameda",
        "South Shore (Alameda)", "9.25", "Alameda",
        "Sunol", "9.25", "Alameda",
        "Union City", "9.75", "Alameda",
        "Warm Springs (Fremont)", "9.25", "Alameda",
        "Bear Valley", "7.25", "Alpine",
        "Hope Valley (Forest Camp)", "7.25", "Alpine",
        "Kirkwood", "7.25", "Alpine",
        "Lake Alpine", "7.25", "Alpine",
        "Markleeville", "7.25", "Alpine",
        "Woodfords", "7.25", "Alpine",
        "Amador City", "7.75", "Amador",
        "Bear River Lake", "7.75", "Amador",
        "Drytown", "7.75", "Amador",
        "Fiddletown", "7.75", "Amador",
        "Ione", "7.75", "Amador",
        "Jackson", "7.75", "Amador",
        "Kit Carson", "7.75", "Amador",
        "Martell", "7.75", "Amador",
        "Pine Grove", "7.75", "Amador",
        "Pioneer", "7.75", "Amador",
        "Plymouth", "7.75", "Amador",
        "River Pines", "7.75", "Amador",
        "Silver Lake", "7.75", "Amador",
        "Sutter Creek", "7.75", "Amador",
        "Volcano", "7.75", "Amador",
        "Bangor", "7.25", "Butte",
        "Berry Creek", "7.25", "Butte",
        "Biggs", "7.25", "Butte",
        "Butte Meadows", "7.25", "Butte",
        "Chico", "7.25", "Butte",
        "Clipper Mills", "7.25", "Butte",
        "Cohasset", "7.25", "Butte",
        "Durham", "7.25", "Butte",
        "Feather Falls", "7.25", "Butte",
        "Forbestown", "7.25", "Butte",
        "Forest Ranch", "7.25", "Butte",
        "Gridley", "7.25", "Butte",
        "Magalia", "7.25", "Butte",
        "Nelson", "7.25", "Butte",
        "Oroville", "7.25", "Butte",
        "Palermo", "7.25", "Butte",
        "Paradise", "7.75", "Butte",
        "Pulga", "7.25", "Butte",
        "Richardson Springs", "7.25", "Butte",
        "Richvale", "7.25", "Butte",
        "Stirling City", "7.25", "Butte",
        "Yankee Hill", "7.25", "Butte",
        "Altaville", "7.25", "Calaveras",
        "Angels Camp", "7.25", "Calaveras",
        "Arnold", "7.25", "Calaveras",
        "Avery", "7.25", "Calaveras",
        "Burson", "7.25", "Calaveras",
        "Camp Connell", "7.25", "Calaveras",
        "Campo Seco", "7.25", "Calaveras",
        "Copperopolis", "7.25", "Calaveras",
        "Douglas Flat", "7.25", "Calaveras",
        "Glencoe", "7.25", "Calaveras",
        "Hathaway Pines", "7.25", "Calaveras",
        "Mokelumne Hill", "7.25", "Calaveras",
        "Mountain Ranch", "7.25", "Calaveras",
        "Murphys", "7.25", "Calaveras",
        "Rail Road Flat", "7.25", "Calaveras",
        "San Andreas", "7.25", "Calaveras",
        "Sheepranch", "7.25", "Calaveras",
        "Vallecito", "7.25", "Calaveras",
        "Valley Springs", "7.25", "Calaveras",
        "Wallace", "7.25", "Calaveras",
        "West Point", "7.25", "Calaveras",
        "White Pines", "7.25", "Calaveras",
        "Wilseyville", "7.25", "Calaveras",
        "Arbuckle", "7.25", "Colusa",
        "College City", "7.25", "Colusa",
        "Colusa", "7.25", "Colusa",
        "Deleven", "7.25", "Colusa",
        "Grimes", "7.25", "Colusa",
        "Maxwell", "7.25", "Colusa",
        "Princeton", "7.25", "Colusa",
        "Sites", "7.25", "Colusa",
        "Stonyford", "7.25", "Colusa",
        "Williams", "7.75", "Colusa",
        "Alamo", "8.25", "Contra Costa",
        "Antioch", "8.75", "Contra Costa",
        "Bay Point (formally West Pittsburg)", "8.25", "Contra Costa",
        "Bethel Island", "8.25", "Contra Costa",
        "Black Hawk", "8.25", "Contra Costa",
        "Brentwood", "8.25", "Contra Costa",
        "Byron", "8.25", "Contra Costa",
        "Canyon", "8.25", "Contra Costa",
        "Clayton", "8.25", "Contra Costa",
        "Concord", "8.75", "Contra Costa",
        "Crockett", "8.25", "Contra Costa",
        "Danville", "8.25", "Contra Costa",
        "Diablo", "8.25", "Contra Costa",
        "Discovery Bay", "8.25", "Contra Costa",
        "Dollar Ranch", "8.25", "Contra Costa",
        "El Cerrito", "9.75", "Contra Costa",
        "El Sobrante", "8.25", "Contra Costa",
        "Fairmount", "8.25", "Contra Costa",
        "Hercules", "8.75", "Contra Costa",
        "Kensington", "8.25", "Contra Costa",
        "Knightsen", "8.25", "Contra Costa",
        "Lafayette", "8.25", "Contra Costa",
        "Martinez", "8.75", "Contra Costa",
        "Mira Vista", "8.25", "Contra Costa",
        "Moraga", "9.25", "Contra Costa",
        "Oakley", "8.25", "Contra Costa",
        "Orinda", "8.75", "Contra Costa",
        "Pacheco", "8.25", "Contra Costa",
        "Pinole", "9.25", "Contra Costa",
        "Pittsburg", "8.75", "Contra Costa",
        "Pleasant Hill", "8.75", "Contra Costa",
        "Port Costa", "8.25", "Contra Costa",
        "Rheem Valley (Moraga)", "9.25", "Contra Costa",
        "Richmond", "9.25", "Contra Costa",
        "Rodeo", "8.25", "Contra Costa",
        "San Pablo", "8.75", "Contra Costa",
        "San Ramon", "8.25", "Contra Costa",
        "Selby", "8.25", "Contra Costa",
        "Shore Acres", "8.25", "Contra Costa",
        "Walnut Creek", "8.25", "Contra Costa",
        "Crescent City", "7.50", "Del Norte",
        "Fort Dick", "7.50", "Del Norte",
        "Gasquet", "7.50", "Del Norte",
        "Klamath", "7.50", "Del Norte",
        "Requa", "7.50", "Del Norte",
        "Smith River", "7.50", "Del Norte",
        "Al Tahoe", "7.25", "El Dorado",
        "Bijou", "7.25", "El Dorado",
        "Cameron Park", "7.25", "El Dorado",
        "Camino", "7.25", "El Dorado",
        "Coloma", "7.25", "El Dorado",
        "Cool", "7.25", "El Dorado",
        "Diamond Springs", "7.25", "El Dorado",
        "Echo Lake", "7.25", "El Dorado",
        "El Dorado", "7.25", "El Dorado",
        "El Dorado Hills", "7.25", "El Dorado",
        "Fallen Leaf", "7.25", "El Dorado",
        "Garden Valley", "7.25", "El Dorado",
        "Georgetown", "7.25", "El Dorado",
        "Greenwood", "7.25", "El Dorado",
        "Grizzly Flats", "7.25", "El Dorado",
        "Kelsey", "7.25", "El Dorado",
        "Kyburz", "7.25", "El Dorado",
        "Little Norway", "7.25", "El Dorado",
        "Lotus", "7.25", "El Dorado",
        "Meeks Bay", "7.25", "El Dorado",
        "Meyers", "7.25", "El Dorado",
        "Mt. Aukum", "7.25", "El Dorado",
        "Nashville", "7.25", "El Dorado",
        "Omo Ranch", "7.25", "El Dorado",
        "Pacific House", "7.25", "El Dorado",
        "Pilot Hill", "7.25", "El Dorado",
        "Placerville", "8.25", "El Dorado",
        "Pollock Pines", "7.25", "El Dorado",
        "Rescue", "7.25", "El Dorado",
        "Shingle Springs", "7.25", "El Dorado",
        "Smithflat", "7.25", "El Dorado",
        "Somerset", "7.25", "El Dorado",
        "South Lake Tahoe", "7.75", "El Dorado",
        "Tahoe Paradise", "7.25", "El Dorado",
        "Tahoe Valley", "7.25", "El Dorado",
        "Twin Bridges", "7.25", "El Dorado",
        "Auberry", "7.98", "Fresno",
        "Barton", "7.98", "Fresno",
        "Big Creek", "7.98", "Fresno",
        "Biola", "7.98", "Fresno",
        "Burrel", "7.98", "Fresno",
        "Calwa", "7.98", "Fresno",
        "Cantua Creek", "7.98", "Fresno",
        "Cardwell", "7.98", "Fresno",
        "Caruthers", "7.98", "Fresno",
        "Cedar Crest", "7.98", "Fresno",
        "Clinter", "7.98", "Fresno",
        "Clovis", "7.98", "Fresno",
        "Coalinga", "7.98", "Fresno",
        "Del Rey", "7.98", "Fresno",
        "Dinkey Creek", "7.98", "Fresno",
        "Dunlap", "7.98", "Fresno",
        "Easton", "7.98", "Fresno",
        "Fancher", "7.98", "Fresno",
        "Fig Garden Village (Fresno)", "7.98", "Fresno",
        "Firebaugh", "7.98", "Fresno",
        "Five Points", "7.98", "Fresno",
        "Fowler", "7.98", "Fresno",
        "Fresno", "7.98", "Fresno",
        "Friant", "7.98", "Fresno",
        "Helm", "7.98", "Fresno",
        "Herndon", "7.98", "Fresno",
        "Highway City (Fresno)", "7.98", "Fresno",
        "Hume", "7.98", "Fresno",
        "Huntington Lake", "7.98", "Fresno",
        "Huron", "8.98", "Fresno",
        "Kerman", "7.98", "Fresno",
        "Kingsburg", "8.98", "Fresno",
        "Lakeshore", "7.98", "Fresno",
        "Laton", "7.98", "Fresno",
        "Malaga", "7.98", "Fresno",
        "Mendota", "7.98", "Fresno",
        "Miramonte", "7.98", "Fresno",
        "Mono Hot Springs", "7.98", "Fresno",
        "Orange Cove", "7.98", "Fresno",
        "Parlier", "7.98", "Fresno",
        "Piedra", "7.98", "Fresno",
        "Pinedale (Fresno)", "7.98", "Fresno",
        "Prather", "7.98", "Fresno",
        "Raisin City", "7.98", "Fresno",
        "Reedley", "8.48", "Fresno",
        "Riverdale", "7.98", "Fresno",
        "San Joaquin", "7.98", "Fresno",
        "Sanger", "8.73", "Fresno",
        "Selma", "8.48", "Fresno",
        "Shaver Lake", "7.98", "Fresno",
        "Squaw Valley", "7.98", "Fresno",
        "Tollhouse", "7.98", "Fresno",
        "Tranquillity", "7.98", "Fresno",
        "Artois", "7.25", "Glenn",
        "Butte City", "7.25", "Glenn",
        "Elk Creek", "7.25", "Glenn",
        "Glenn", "7.25", "Glenn",
        "Hamilton City", "7.25", "Glenn",
        "Ordbend", "7.25", "Glenn",
        "Orland", "7.75", "Glenn",
        "Willows", "7.25", "Glenn",
        "Alderpoint", "7.75", "Humboldt",
        "Alton", "7.75", "Humboldt",
        "Arcata", "8.50", "Humboldt",
        "Bayside", "7.75", "Humboldt",
        "Blocksburg", "7.75", "Humboldt",
        "Blue Lake", "7.75", "Humboldt",
        "Briceland", "7.75", "Humboldt",
        "Bridgeville", "7.75", "Humboldt",
        "Carlotta", "7.75", "Humboldt",
        "Crannell", "7.75", "Humboldt",
        "Cutten", "7.75", "Humboldt",
        "Ettersburg", "7.75", "Humboldt",
        "Eureka", "8.50", "Humboldt",
        "Fernbridge (Fortuna)", "7.75", "Humboldt",
        "Ferndale", "7.75", "Humboldt",
        "Fields Landing", "7.75", "Humboldt",
        "Fort Seward", "7.75", "Humboldt",
        "Fortuna", "8.50", "Humboldt",
        "Freshwater", "7.75", "Humboldt",
        "Garberville", "7.75", "Humboldt",
        "Harris", "7.75", "Humboldt",
        "Holmes", "7.75", "Humboldt",
        "Honeydew", "7.75", "Humboldt",
        "Hoopa", "7.75", "Humboldt",
        "Hydesville", "7.75", "Humboldt",
        "Kneeland", "7.75", "Humboldt",
        "Korbel", "7.75", "Humboldt",
        "Loleta", "7.75", "Humboldt",
        "McKinleyville", "7.75", "Humboldt",
        "Miranda", "7.75", "Humboldt",
        "Myers Flat", "7.75", "Humboldt",
        "Orick", "7.75", "Humboldt",
        "Orleans", "7.75", "Humboldt",
        "Pepperwood", "7.75", "Humboldt",
        "Petrolia", "7.75", "Humboldt",
        "Phillipsville", "7.75", "Humboldt",
        "Redcrest", "7.75", "Humboldt",
        "Redway", "7.75", "Humboldt",
        "Richardson Grove", "7.75", "Humboldt",
        "Rio Dell", "8.75", "Humboldt",
        "Rohnerville", "7.75", "Humboldt",
        "Ruby Valley", "7.75", "Humboldt",
        "Samoa", "7.75", "Humboldt",
        "Scotia", "7.75", "Humboldt",
        "Shively", "7.75", "Humboldt",
        "South Fork", "7.75", "Humboldt",
        "Trinidad", "8.50", "Humboldt",
        "Weott", "7.75", "Humboldt",
        "Westhaven", "7.75", "Humboldt",
        "Whitethorn", "7.75", "Humboldt",
        "Whitlow", "7.75", "Humboldt",
        "Willow Creek", "7.75", "Humboldt",
        "Bard", "7.75", "Imperial",
        "Bombay Beach", "7.75", "Imperial",
        "Brawley", "7.75", "Imperial",
        "Calexico", "8.25", "Imperial",
        "Calipatria", "7.75", "Imperial",
        "El Centro", "8.25", "Imperial",
        "Heber", "7.75", "Imperial",
        "Holtville", "7.75", "Imperial",
        "Imperial", "7.75", "Imperial",
        "Niland", "7.75", "Imperial",
        "Ocotillo", "7.75", "Imperial",
        "Palo Verde", "7.75", "Imperial",
        "Plaster City", "7.75", "Imperial",
        "Salton City", "7.75", "Imperial",
        "Seeley", "7.75", "Imperial",
        "Westmorland", "7.75", "Imperial",
        "Winterhaven", "7.75", "Imperial",
        "Amargosa (Death Valley)", "7.75", "Inyo",
        "Bartlett", "7.75", "Inyo",
        "Big Pine", "7.75", "Inyo",
        "Bishop", "7.75", "Inyo",
        "Cartago", "7.75", "Inyo",
        "Coso Junction", "7.75", "Inyo",
        "Darwin", "7.75", "Inyo",
        "Death Valley", "7.75", "Inyo",
        "Death Valley Junction", "7.75", "Inyo",
        "Independence", "7.75", "Inyo",
        "Inyo", "7.75", "Inyo",
        "Keeler", "7.75", "Inyo",
        "Laws", "7.75", "Inyo",
        "Little Lake", "7.75", "Inyo",
        "Lone Pine", "7.75", "Inyo",
        "Olancha", "7.75", "Inyo",
        "Shoshone", "7.75", "Inyo",
        "Swall Meadows (Bishop)", "7.75", "Inyo",
        "Tecopa", "7.75", "Inyo",
        "Arvin", "8.25", "Kern",
        "Bakersfield", "7.25", "Kern",
        "Bodfish", "7.25", "Kern",
        "Boron", "7.25", "Kern",
        "Buttonwillow", "7.25", "Kern",
        "Caliente", "7.25", "Kern",
        "California City", "7.25", "Kern",
        "Cantil", "7.25", "Kern",
        "China Lake NWC (Ridgecrest)", "8.25", "Kern",
        "Del Kern (Bakersfield)", "7.25", "Kern",
        "Delano", "8.25", "Kern",
        "Di Giorgio", "7.25", "Kern",
        "Edison", "7.25", "Kern",
        "Edwards", "7.25", "Kern",
        "Edwards A.F.B.", "7.25", "Kern",
        "Fellows", "7.25", "Kern",
        "Frazier Park", "7.25", "Kern",
        "Glennville", "7.25", "Kern",
        "Golden Hills", "7.25", "Kern",
        "Greenacres", "7.25", "Kern",
        "Homestead", "7.25", "Kern",
        "Inyokern", "7.25", "Kern",
        "Johannesburg", "7.25", "Kern",
        "Keene", "7.25", "Kern",
        "Kernville", "7.25", "Kern",
        "La Cresta Village", "7.25", "Kern",
        "Lake Isabella", "7.25", "Kern",
        "Lamont", "7.25", "Kern",
        "Lebec", "7.25", "Kern",
        "Lost Hills", "7.25", "Kern",
        "Maricopa", "7.25", "Kern",
        "McFarland", "7.25", "Kern",
        "McKittrick", "7.25", "Kern",
        "Mettler", "7.25", "Kern",
        "Miracle Hot Springs", "7.25", "Kern",
        "Mojave", "7.25", "Kern",
        "Monolith", "7.25", "Kern",
        "Mountain Mesa", "7.25", "Kern",
        "North Edwards", "7.25", "Kern",
        "Oildale", "7.25", "Kern",
        "Onyx", "7.25", "Kern",
        "Pond", "7.25", "Kern",
        "Pumpkin Center", "7.25", "Kern",
        "Randsburg", "7.25", "Kern",
        "Ridgecrest", "8.25", "Kern",
        "Rio Bravo (Bakersfield)", "7.25", "Kern",
        "Rosamond", "7.25", "Kern",
        "Shafter", "7.25", "Kern",
        "Taft", "7.25", "Kern",
        "Tehachapi", "7.25", "Kern",
        "Tupman", "7.25", "Kern",
        "Vista Park", "7.25", "Kern",
        "Wasco", "8.25", "Kern",
        "Weldon", "7.25", "Kern",
        "Wheeler Ridge", "7.25", "Kern",
        "Wofford Heights", "7.25", "Kern",
        "Woody", "7.25", "Kern",
        "Armona", "7.25", "Kings",
        "Avenal", "7.25", "Kings",
        "Corcoran", "8.25", "Kings",
        "Hanford", "7.25", "Kings",
        "Kettleman City", "7.25", "Kings",
        "Lemoore", "7.25", "Kings",
        "Naval Air Station (Lemoore)", "7.25", "Kings",
        "Stratford", "7.25", "Kings",
        "Clearlake Highlands (Clearlake)", "8.75", "Lake",
        "Clearlake Oaks", "7.25", "Lake",
        "Clearlake Park (Clearlake)", "8.75", "Lake",
        "Clearlake", "8.75", "Lake",
        "Cobb", "7.25", "Lake",
        "Finley", "7.25", "Lake",
        "Glenhaven", "7.25", "Lake",
        "Hobergs", "7.25", "Lake",
        "Kelseyville", "7.25", "Lake",
        "Lakeport", "8.75", "Lake",
        "Loch Lomond", "7.25", "Lake",
        "Lower Lake", "7.25", "Lake",
        "Lucerne", "7.25", "Lake",
        "Middletown", "7.25", "Lake",
        "Nice", "7.25", "Lake",
        "Upper Lake/ Upper Lake Valley", "7.25", "Lake",
        "Whispering Pines", "7.25", "Lake",
        "Witter Springs", "7.25", "Lake",
        "Bieber", "7.25", "Lassen",
        "Doyle", "7.25", "Lassen",
        "Herlong", "7.25", "Lassen",
        "Horse Lake", "7.25", "Lassen",
        "Janesville", "7.25", "Lassen",
        "Johnstonville", "7.25", "Lassen",
        "Juniper", "7.25", "Lassen",
        "Litchfield", "7.25", "Lassen",
        "Little Valley", "7.25", "Lassen",
        "Madeline", "7.25", "Lassen",
        "Milford", "7.25", "Lassen",
        "Nubieber", "7.25", "Lassen",
        "Ravendale", "7.25", "Lassen",
        "Standish", "7.25", "Lassen",
        "Susanville", "7.25", "Lassen",
        "Termo", "7.25", "Lassen",
        "Wendel", "7.25", "Lassen",
        "Westwood", "7.25", "Lassen",
        "Acton", "9.50", "Los Angeles",
        "Agoura", "9.50", "Los Angeles",
        "Agoura Hills", "9.50", "Los Angeles",
        "Agua Dulce", "9.50", "Los Angeles",
        "Alhambra", "9.50", "Los Angeles",
        "Almondale", "9.50", "Los Angeles",
        "Alondra", "9.50", "Los Angeles",
        "Altadena", "9.50", "Los Angeles",
        "Antelope Acres", "9.50", "Los Angeles",
        "Arcadia", "9.50", "Los Angeles",
        "Arleta (Los Angeles)", "9.50", "Los Angeles",
        "Artesia", "9.50", "Los Angeles",
        "Athens", "9.50", "Los Angeles",
        "Avalon", "10.00", "Los Angeles",
        "Azusa", "9.50", "Los Angeles",
        "Bailey", "9.50", "Los Angeles",
        "Baldwin Park", "9.50", "Los Angeles",
        "Barrington", "9.50", "Los Angeles",
        "Bassett", "9.50", "Los Angeles",
        "Bel Air Estates (Los Angeles)", "9.50", "Los Angeles",
        "Bell Gardens", "9.50", "Los Angeles",
        "Bell", "9.50", "Los Angeles",
        "Bellflower", "9.50", "Los Angeles",
        "Beverly Hills", "9.50", "Los Angeles",
        "Biola College (La Mirada)", "9.50", "Los Angeles",
        "Bouquet Canyon (Santa Clarita)", "9.50", "Los Angeles",
        "Bradbury", "9.50", "Los Angeles",
        "Brents Junction", "9.50", "Los Angeles",
        "Brentwood (Los Angeles)", "9.50", "Los Angeles",
        "Burbank", "9.50", "Los Angeles",
        "Cabrillo", "9.50", "Los Angeles",
        "Calabasas Highlands", "9.50", "Los Angeles",
        "Calabasas Park", "9.50", "Los Angeles",
        "Calabasas", "9.50", "Los Angeles",
        "Canoga Annex", "9.50", "Los Angeles",
        "Canoga Park (Los Angeles)", "9.50", "Los Angeles",
        "Canyon Country (Santa Clarita)", "9.50", "Los Angeles",
        "Carson", "9.50", "Los Angeles",
        "Castaic", "9.50", "Los Angeles",
        "Cedar", "9.50", "Los Angeles",
        "Century City (Los Angeles)", "9.50", "Los Angeles",
        "Cerritos", "9.50", "Los Angeles",
        "Charter Oak", "9.50", "Los Angeles",
        "Chatsworth (Los Angeles)", "9.50", "Los Angeles",
        "City of Commerce", "10.00", "Los Angeles",
        "City of Industry", "9.50", "Los Angeles",
        "City Terrace", "9.50", "Los Angeles",
        "Claremont", "9.50", "Los Angeles",
        "Cole", "9.50", "Los Angeles",
        "Commerce", "10.00", "Los Angeles",
        "Compton", "10.25", "Los Angeles",
        "Cornell", "9.50", "Los Angeles",
        "Covina", "9.50", "Los Angeles",
        "Crenshaw (Los Angeles)", "9.50", "Los Angeles",
        "Cudahy", "9.50", "Los Angeles",
        "Culver City", "10.00", "Los Angeles",
        "Del Sur", "9.50", "Los Angeles",
        "Diamond Bar", "9.50", "Los Angeles",
        "Downey", "10.00", "Los Angeles",
        "Duarte", "9.50", "Los Angeles",
        "Eagle Rock (Los Angeles)", "9.50", "Los Angeles",
        "East Los Angeles", "9.50", "Los Angeles",
        "East Lynwood (Lynwood)", "10.25", "Los Angeles",
        "East Rancho Dominguez", "9.50", "Los Angeles",
        "East San Pedro (Los Angeles)", "9.50", "Los Angeles",
        "Eastgate", "9.50", "Los Angeles",
        "Echo Park (Los Angeles)", "9.50", "Los Angeles",
        "El Monte", "10.00", "Los Angeles",
        "El Segundo", "9.50", "Los Angeles",
        "Elizabeth Lake", "9.50", "Los Angeles",
        "Encino (Los Angeles)", "9.50", "Los Angeles",
        "Flintridge (LaCanada/ Flintridge)", "9.50", "Los Angeles",
        "Florence", "9.50", "Los Angeles",
        "Forest Park", "9.50", "Los Angeles",
        "Friendly Valley (Santa Clarita)", "9.50", "Los Angeles",
        "Gardena", "9.50", "Los Angeles",
        "Glassell Park (Los Angeles)", "9.50", "Los Angeles",
        "Glendale", "9.50", "Los Angeles",
        "Glendora", "9.50", "Los Angeles",
        "Gorman", "9.50", "Los Angeles",
        "Granada Hills (Los Angeles)", "9.50", "Los Angeles",
        "Green Valley", "9.50", "Los Angeles",
        "Hacienda Heights", "9.50", "Los Angeles",
        "Harbor City (Los Angeles)", "9.50", "Los Angeles",
        "Hawaiian Gardens", "9.50", "Los Angeles",
        "Hawthorne", "10.25", "Los Angeles",
        "Hazard", "9.50", "Los Angeles",
        "Hermosa Beach", "9.50", "Los Angeles",
        "Hidden Hills", "9.50", "Los Angeles",
        "Highland Park (Los Angeles)", "9.50", "Los Angeles",
        "Hollywood (Los Angeles)", "9.50", "Los Angeles",
        "Honby", "9.50", "Los Angeles",
        "Huntington Park", "10.25", "Los Angeles",
        "Hyde Park (Los Angeles)", "9.50", "Los Angeles",
        "Industry", "9.50", "Los Angeles",
        "Inglewood", "10.00", "Los Angeles",
        "Irwindale", "9.50", "Los Angeles",
        "Kagel Canyon", "9.50", "Los Angeles",
        "L.A. Airport (Los Angeles)", "9.50", "Los Angeles",
        "La Canada- Flintridge", "9.50", "Los Angeles",
        "La Crescenta", "9.50", "Los Angeles",
        "La Habra Heights", "9.50", "Los Angeles",
        "La Mirada", "9.50", "Los Angeles",
        "La Puente", "9.50", "Los Angeles",
        "La Verne", "9.50", "Los Angeles",
        "La Vina", "9.50", "Los Angeles",
        "Ladera Heights", "9.50", "Los Angeles",
        "Lake Hughes", "9.50", "Los Angeles",
        "Lake Los Angeles", "9.50", "Los Angeles",
        "Lakeview Terrace (Los Angeles)", "9.50", "Los Angeles",
        "Lakewood", "9.50", "Los Angeles",
        "Lancaster", "9.50", "Los Angeles",
        "Lang", "9.50", "Los Angeles",
        "Lawndale", "9.50", "Los Angeles",
        "Lennox", "9.50", "Los Angeles",
        "Leona Valley", "9.50", "Los Angeles",
        "Lincoln Heights (Los Angeles)", "9.50", "Los Angeles",
        "Littlerock (Also Little Rock)", "9.50", "Los Angeles",
        "Llano", "9.50", "Los Angeles",
        "Lomita", "9.50", "Los Angeles",
        "Long Beach", "10.25", "Los Angeles",
        "Longview", "9.50", "Los Angeles",
        "Los Angeles", "9.50", "Los Angeles",
        "Los Nietos", "9.50", "Los Angeles",
        "Lugo", "9.50", "Los Angeles",
        "Lynwood", "10.25", "Los Angeles",
        "Maclay", "9.50", "Los Angeles",
        "Malibu", "9.50", "Los Angeles",
        "Manhattan Beach", "9.50", "Los Angeles",
        "Mar Vista", "9.50", "Los Angeles",
        "Marcelina", "9.50", "Los Angeles",
        "Marina Del Rey", "9.50", "Los Angeles",
        "Maywood", "9.50", "Los Angeles",
        "Mint Canyon", "9.50", "Los Angeles",
        "Mission Hills (Los Angeles)", "9.50", "Los Angeles",
        "Moneta", "9.50", "Los Angeles",
        "Monrovia", "9.50", "Los Angeles",
        "Montebello", "9.50", "Los Angeles",
        "Monterey Park", "9.50", "Los Angeles",
        "Montrose", "9.50", "Los Angeles",
        "Mount Wilson", "9.50", "Los Angeles",
        "Naples", "9.50", "Los Angeles",
        "Newhall (Santa Clarita)", "9.50", "Los Angeles",
        "North Gardena", "9.50", "Los Angeles",
        "North Hills (Los Angeles)", "9.50", "Los Angeles",
        "North Hollywood (Los Angeles)", "9.50", "Los Angeles",
        "Northridge (Los Angeles)", "9.50", "Los Angeles",
        "Norwalk", "9.50", "Los Angeles",
        "Oban", "9.50", "Los Angeles",
        "Olive View (Los Angeles)", "9.50", "Los Angeles",
        "Pacific Palisades (Los Angeles)", "9.50", "Los Angeles",
        "Pacoima (Los Angeles)", "9.50", "Los Angeles",
        "Pallett", "9.50", "Los Angeles",
        "Palmdale", "9.50", "Los Angeles",
        "Palos Verdes Estates", "9.50", "Los Angeles",
        "Palos Verdes/Peninsula", "9.50", "Los Angeles",
        "Panorama City (Los Angeles)", "9.50", "Los Angeles",
        "Paramount", "9.50", "Los Angeles",
        "Pasadena", "9.50", "Los Angeles",
        "Pearblossom", "9.50", "Los Angeles",
        "Pearland", "9.50", "Los Angeles",
        "Perry (Whittier)", "9.50", "Los Angeles",
        "Pico Rivera", "10.25", "Los Angeles",
        "Pinetree", "9.50", "Los Angeles",
        "Playa Del Rey (Los Angeles)", "9.50", "Los Angeles",
        "Pomona", "9.50", "Los Angeles",
        "Porter Ranch (Los Angeles)", "9.50", "Los Angeles",
        "Portuguese Bend (Rancho Palos Verdes)", "9.50", "Los Angeles",
        "Pt. Dume", "9.50", "Los Angeles",
        "Quartz Hill", "9.50", "Los Angeles",
        "Rancho Dominguez", "9.50", "Los Angeles",
        "Rancho Palos Verdes", "9.50", "Los Angeles",
        "Rancho Park (Los Angeles)", "9.50", "Los Angeles",
        "Ravenna", "9.50", "Los Angeles",
        "Redondo Beach", "9.50", "Los Angeles",
        "Reseda (Los Angeles)", "9.50", "Los Angeles",
        "Rimpau (Los Angeles)", "9.50", "Los Angeles",
        "Rolling Hills Estates", "9.50", "Los Angeles",
        "Rolling Hills", "9.50", "Los Angeles",
        "Rose Bowl (Pasadena)", "9.50", "Los Angeles",
        "Rosemead", "9.50", "Los Angeles",
        "Rowland Heights", "9.50", "Los Angeles",
        "San Dimas", "9.50", "Los Angeles",
        "San Fernando", "10.00", "Los Angeles",
        "San Gabriel", "9.50", "Los Angeles",
        "San Marino", "9.50", "Los Angeles",
        "San Pedro (Los Angeles)", "9.50", "Los Angeles",
        "Santa Clarita", "9.50", "Los Angeles",
        "Santa Fe Springs", "9.50", "Los Angeles",
        "Santa Monica", "10.25", "Los Angeles",
        "Saugus (Santa Clarita)", "9.50", "Los Angeles",
        "Sawtelle (Los Angeles)", "9.50", "Los Angeles",
        "Seminole Hot Springs", "9.50", "Los Angeles",
        "Sepulveda (Los Angeles)", "9.50", "Los Angeles",
        "Shadow Hills (Los Angeles)", "9.50", "Los Angeles",
        "Sherman Oaks (Los Angeles)", "9.50", "Los Angeles",
        "Sierra Madre", "9.50", "Los Angeles",
        "Signal Hill", "9.50", "Los Angeles",
        "Sleepy Valley", "9.50", "Los Angeles",
        "Solemint", "9.50", "Los Angeles",
        "South El Monte", "10.00", "Los Angeles",
        "South Gate", "10.25", "Los Angeles",
        "South Pasadena", "9.50", "Los Angeles",
        "South Whittier", "9.50", "Los Angeles",
        "Stevenson Ranch", "9.50", "Los Angeles",
        "Studio City (Los Angeles)", "9.50", "Los Angeles",
        "Sulphur Springs", "9.50", "Los Angeles",
        "Sun Valley (Los Angeles)", "9.50", "Los Angeles",
        "Sunland (Los Angeles)", "9.50", "Los Angeles",
        "Sylmar (Los Angeles)", "9.50", "Los Angeles",
        "Tarzana (Los Angeles)", "9.50", "Los Angeles",
        "Temple City", "9.50", "Los Angeles",
        "Terminal Island (Los Angeles)", "9.50", "Los Angeles",
        "Toluca Lake (Los Angeles)", "9.50", "Los Angeles",
        "Topanga", "9.50", "Los Angeles",
        "Topanga Park", "9.50", "Los Angeles",
        "Torrance", "9.50", "Los Angeles",
        "Tujunga (Los Angeles)", "9.50", "Los Angeles",
        "Universal City", "9.50", "Los Angeles",
        "Val Verde Park", "9.50", "Los Angeles",
        "Valencia (Santa Clarita)", "9.50", "Los Angeles",
        "Valinda", "9.50", "Los Angeles",
        "Valley Village", "9.50", "Los Angeles",
        "Valyermo", "9.50", "Los Angeles",
        "Van Nuys (Los Angeles)", "9.50", "Los Angeles",
        "Vasquez Rocks", "9.50", "Los Angeles",
        "Venice (Los Angeles)", "9.50", "Los Angeles",
        "Verdugo City (Glendale)", "9.50", "Los Angeles",
        "Vernon", "9.50", "Los Angeles",
        "Veteran's Hospital (Los Angeles)", "9.50", "Los Angeles",
        "View Park", "9.50", "Los Angeles",
        "Vincent", "9.50", "Los Angeles",
        "Walnut Park", "9.50", "Los Angeles",
        "Walnut", "9.50", "Los Angeles",
        "Watts", "9.50", "Los Angeles",
        "West Covina", "9.50", "Los Angeles",
        "West Hills (Los Angeles)", "9.50", "Los Angeles",
        "West Hollywood", "9.50", "Los Angeles",
        "West Los Angeles (Los Angeles)", "9.50", "Los Angeles",
        "Westchester (Los Angeles)", "9.50", "Los Angeles",
        "Westlake (Los Angeles)", "9.50", "Los Angeles",
        "Westlake Village", "9.50", "Los Angeles",
        "Westwood (Los Angeles)", "9.50", "Los Angeles",
        "Whittier", "9.50", "Los Angeles",
        "Willowbrook", "9.50", "Los Angeles",
        "Wilmington (Los Angeles)", "9.50", "Los Angeles",
        "Wilsona Gardens", "9.50", "Los Angeles",
        "Windsor Hills", "9.50", "Los Angeles",
        "Winnetka (Los Angeles)", "9.50", "Los Angeles",
        "Woodland Hills (Los Angeles)", "9.50", "Los Angeles",
        "Ahwahnee", "7.75", "Madera",
        "Bass Lake", "7.75", "Madera",
        "Chowchilla", "7.75", "Madera",
        "Coarsegold", "7.75", "Madera",
        "Madera", "8.25", "Madera",
        "North Fork", "7.75", "Madera",
        "Oakhurst", "7.75", "Madera",
        "O'Neals", "7.75", "Madera",
        "Raymond", "7.75", "Madera",
        "Red Top", "7.75", "Madera",
        "Wishon", "7.75", "Madera",
        "Belvedere", "8.25", "Marin",
        "Bolinas", "8.25", "Marin",
        "Corte Madera", "9.00", "Marin",
        "Dillon Beach", "8.25", "Marin",
        "Dogtown", "8.25", "Marin",
        "Fairfax", "9.00", "Marin",
        "Fallon", "8.25", "Marin",
        "Forest Knolls", "8.25", "Marin",
        "Greenbrae (Larkspur)", "9.00", "Marin",
        "Hamilton A.F.B. (Novato)", "8.50", "Marin",
        "Ignacio (Novato)", "8.50", "Marin",
        "Inverness", "8.25", "Marin",
        "Kentfield", "8.25", "Marin",
        "Lagunitas", "8.25", "Marin",
        "Larkspur", "9.00", "Marin",
        "Marin City", "8.25", "Marin",
        "Marshall", "8.25", "Marin",
        "Mill Valley", "8.25", "Marin",
        "Nicasio", "8.25", "Marin",
        "Novato", "8.50", "Marin",
        "Olema", "8.25", "Marin",
        "Point Reyes Station", "8.25", "Marin",
        "Ross", "8.25", "Marin",
        "San Anselmo", "8.75", "Marin",
        "San Geronimo", "8.25", "Marin",
        "San Quentin", "8.25", "Marin",
        "San Rafael", "9.00", "Marin",
        "Sausalito", "8.75", "Marin",
        "Stinson Beach", "8.25", "Marin",
        "Tamal (San Quentin)", "8.25", "Marin",
        "Tiburon", "8.25", "Marin",
        "Tomales", "8.25", "Marin",
        "Woodacre", "8.25", "Marin",
        "Bear Valley", "7.75", "Mariposa",
        "Bridgeport", "7.75", "Mariposa",
        "Camp Curry", "7.75", "Mariposa",
        "Catheys Valley", "7.75", "Mariposa",
        "Colorado", "7.75", "Mariposa",
        "Coulterville", "7.75", "Mariposa",
        "Curry Village", "7.75", "Mariposa",
        "El Portal", "7.75", "Mariposa",
        "Fish Camp", "7.75", "Mariposa",
        "Hornitos", "7.75", "Mariposa",
        "Mariposa", "7.75", "Mariposa",
        "Midpines", "7.75", "Mariposa",
        "Tuolumne Meadows", "7.75", "Mariposa",
        "Wawona", "7.75", "Mariposa",
        "Yosemite Lodge", "7.75", "Mariposa",
        "Yosemite National Park", "7.75", "Mariposa",
        "Albion", "7.88", "Mendocino",
        "Boonville", "7.88", "Mendocino",
        "Branscomb", "7.88", "Mendocino",
        "Calpella", "7.88", "Mendocino",
        "Caspar", "7.88", "Mendocino",
        "Comptche", "7.88", "Mendocino",
        "Covelo", "7.88", "Mendocino",
        "Cummings", "7.88", "Mendocino",
        "Dos Rios", "7.88", "Mendocino",
        "Elk", "7.88", "Mendocino",
        "Fort Bragg", "8.88", "Mendocino",
        "Gualala", "7.88", "Mendocino",
        "Hopland", "7.88", "Mendocino",
        "Laytonville", "7.88", "Mendocino",
        "Leggett", "7.88", "Mendocino",
        "Littleriver", "7.88", "Mendocino",
        "Mendocino", "7.88", "Mendocino",
        "Navarro", "7.88", "Mendocino",
        "Philo", "7.88", "Mendocino",
        "Piercy", "7.88", "Mendocino",
        "Point Arena", "8.38", "Mendocino",
        "Potter Valley", "7.88", "Mendocino",
        "Redwood Valley", "7.88", "Mendocino",
        "Spyrock", "7.88", "Mendocino",
        "Talmage", "7.88", "Mendocino",
        "Ukiah", "8.88", "Mendocino",
        "Westport", "7.88", "Mendocino",
        "Willits", "8.38", "Mendocino",
        "Yorkville", "7.88", "Mendocino",
        "Atwater", "8.25", "Merced",
        "Ballico", "7.75", "Merced",
        "Castle A.F.B.", "7.75", "Merced",
        "Cressey", "7.75", "Merced",
        "Delhi", "7.75", "Merced",
        "Dos Palos", "7.75", "Merced",
        "El Nido", "7.75", "Merced",
        "Gustine", "8.25", "Merced",
        "Hilmar", "7.75", "Merced",
        "Le Grand (Also Legrand)", "7.75", "Merced",
        "Livingston", "7.75", "Merced",
        "Los Banos", "8.25", "Merced",
        "Merced", "8.25", "Merced",
        "Planada", "7.75", "Merced",
        "Santa Nella", "7.75", "Merced",
        "Santa Rita Park", "7.75", "Merced",
        "Snelling", "7.75", "Merced",
        "South Dos Palos", "7.75", "Merced",
        "Stevinson", "7.75", "Merced",
        "Volta", "7.75", "Merced",
        "Winton", "7.75", "Merced",
        "Adin", "7.25", "Modoc",
        "Alturas", "7.25", "Modoc",
        "Canby", "7.25", "Modoc",
        "Cedarville", "7.25", "Modoc",
        "Davis Creek", "7.25", "Modoc",
        "Eagleville", "7.25", "Modoc",
        "Fort Bidwell", "7.25", "Modoc",
        "Lake City", "7.25", "Modoc",
        "Likely", "7.25", "Modoc",
        "Lookout", "7.25", "Modoc",
        "Willow Ranch", "7.25", "Modoc",
        "Benton", "7.25", "Mono",
        "Bridgeport", "7.25", "Mono",
        "Coleville", "7.25", "Mono",
        "Crowley Lake", "7.25", "Mono",
        "June Lake", "7.25", "Mono",
        "Lake Mary", "7.25", "Mono",
        "Lee Vining", "7.25", "Mono",
        "Mammoth Lakes", "7.75", "Mono",
        "Mono Lake", "7.25", "Mono",
        "Sherwin Plaza", "7.25", "Mono",
        "Toms Place", "7.25", "Mono",
        "Topaz", "7.25", "Mono",
        "Aromas", "7.75", "Monterey",
        "Big Sur", "7.75", "Monterey",
        "Bradley", "7.75", "Monterey",
        "Camp Roberts", "7.75", "Monterey",
        "Carmel Rancho", "7.75", "Monterey",
        "Carmel Valley", "7.75", "Monterey",
        "Carmel", "8.75", "Monterey",
        "Castroville", "7.75", "Monterey",
        "Chualar", "7.75", "Monterey",
        "Del Monte Grove (Monterey)", "8.75", "Monterey",
        "Del Rey Oaks", "9.25", "Monterey",
        "Fort Ord", "7.75", "Monterey",
        "Fort Ord (Marina)", "8.75", "Monterey",
        "Fort Ord (Seaside)", "9.25", "Monterey",
        "Gonzales", "8.25", "Monterey",
        "Greenfield", "9.50", "Monterey",
        "Jolon", "7.75", "Monterey",
        "King City", "8.25", "Monterey",
        "Lockwood", "7.75", "Monterey",
        "Lucia", "7.75", "Monterey",
        "Marina", "8.75", "Monterey",
        "Monterey", "8.75", "Monterey",
        "Moss Landing", "7.75", "Monterey",
        "Pacific Grove", "8.75", "Monterey",
        "Pajaro", "7.75", "Monterey",
        "Parkfield", "7.75", "Monterey",
        "Pebble Beach", "7.75", "Monterey",
        "Presidio of Monterey (Monterey)", "8.75", "Monterey",
        "Priest Valley", "7.75", "Monterey",
        "Prunedale", "7.75", "Monterey",
        "Royal Oaks", "7.75", "Monterey",
        "Salinas", "9.25", "Monterey",
        "San Ardo", "7.75", "Monterey",
        "San Lucas", "7.75", "Monterey",
        "Sand City", "8.75", "Monterey",
        "Seaside", "9.25", "Monterey",
        "Soledad", "8.75", "Monterey",
        "Spreckels", "7.75", "Monterey",
        "U.S. Naval Postgrad School (Monterey)", "8.75", "Monterey",
        "American Canyon", "7.75", "Napa",
        "Angwin", "7.75", "Napa",
        "Calistoga", "7.75", "Napa",
        "Deer Park", "7.75", "Napa",
        "Imola (Napa)", "7.75", "Napa",
        "Napa", "7.75", "Napa",
        "Oakville", "7.75", "Napa",
        "Pope Valley", "7.75", "Napa",
        "Rutherford", "7.75", "Napa",
        "Saint Helena", "8.25", "Napa",
        "Spanish Flat", "7.75", "Napa",
        "St. Helena", "8.25", "Napa",
        "Steele Park", "7.75", "Napa",
        "Yountville", "7.75", "Napa",
        "Cedar Ridge", "7.50", "Nevada",
        "Chicago Park", "7.50", "Nevada",
        "Floriston", "7.50", "Nevada",
        "Grass Valley", "8.50", "Nevada",
        "Lake City", "7.50", "Nevada",
        "Nevada City", "8.38", "Nevada",
        "Norden", "7.50", "Nevada",
        "North San Juan", "7.50", "Nevada",
        "Penn Valley", "7.50", "Nevada",
        "Rough and Ready", "7.50", "Nevada",
        "Soda Springs", "7.50", "Nevada",
        "Truckee", "8.25", "Nevada",
        "Aliso Viejo", "7.75", "Orange",
        "Anaheim", "7.75", "Orange",
        "Atwood", "7.75", "Orange",
        "Balboa (Newport Beach)", "7.75", "Orange",
        "Balboa Island (Newport Beach)", "7.75", "Orange",
        "Ballroad", "7.75", "Orange",
        "Bolsa", "7.75", "Orange",
        "Brea", "7.75", "Orange",
        "Brookhurst Center", "7.75", "Orange",
        "Buena Park", "7.75", "Orange",
        "Capistrano Beach (Dana Point)", "7.75", "Orange",
        "Corona Del Mar (Newport Beach)", "7.75", "Orange",
        "Costa Mesa", "7.75", "Orange",
        "Coto De Caza", "7.75", "Orange",
        "Cowan Heights", "7.75", "Orange",
        "Dana Point", "7.75", "Orange",
        "East Irvine (Irvine)", "7.75", "Orange",
        "El Modena", "7.75", "Orange",
        "El Toro (Lake Forest)", "7.75", "Orange",
        "El Toro M.C.A.S.", "7.75", "Orange",
        "Foothill Ranch", "7.75", "Orange",
        "Fountain Valley", "8.75", "Orange",
        "Fullerton", "7.75", "Orange",
        "Garden Grove", "7.75", "Orange",
        "Huntington", "7.75", "Orange",
        "Huntington Beach", "7.75", "Orange",
        "Irvine", "7.75", "Orange",
        "La Habra", "8.25", "Orange",
        "La Palma", "8.75", "Orange",
        "Ladera Ranch", "7.75", "Orange",
        "Laguna Beach", "7.75", "Orange",
        "Laguna Hills", "7.75", "Orange",
        "Laguna Niguel", "7.75", "Orange",
        "Laguna Woods", "7.75", "Orange",
        "Lake Forest", "7.75", "Orange",
        "Leisure World", "7.75", "Orange",
        "Leisure World (Seal Beach)", "7.75", "Orange",
        "Los Alamitos", "7.75", "Orange",
        "Mariner", "7.75", "Orange",
        "Midway City", "7.75", "Orange",
        "Mission Viejo", "7.75", "Orange",
        "Monarch Beach (Dana Point)", "7.75", "Orange",
        "Newport Beach", "7.75", "Orange",
        "Orange", "7.75", "Orange",
        "Placentia", "7.75", "Orange",
        "Rancho Santa Margarita", "7.75", "Orange",
        "Rossmoor", "7.75", "Orange",
        "San Clemente", "7.75", "Orange",
        "San Juan Capistrano", "7.75", "Orange",
        "San Juan Plaza (San Juan Capistrano)", "7.75", "Orange",
        "Santa Ana", "7.75", "Orange",
        "Seal Beach", "7.75", "Orange",
        "Silverado Canyon", "7.75", "Orange",
        "South Laguna (Laguna Beach)", "7.75", "Orange",
        "Stanton", "8.75", "Orange",
        "Sunset Beach", "7.75", "Orange",
        "Surfside (Seal Beach)", "7.75", "Orange",
        "Trabuco Canyon", "7.75", "Orange",
        "Tustin", "7.75", "Orange",
        "University Park (Irvine)", "7.75", "Orange",
        "Villa Park", "7.75", "Orange",
        "Westminster", "8.75", "Orange",
        "Yorba Linda", "7.75", "Orange",
        "Cypress", "7.75", "Orange ",
        "Alta", "7.25", "Placer",
        "Applegate", "7.25", "Placer",
        "Auburn", "7.25", "Placer",
        "Baxter", "7.25", "Placer",
        "Bowman", "7.25", "Placer",
        "Carnelian Bay", "7.25", "Placer",
        "Chambers Lodge", "7.25", "Placer",
        "Colfax", "7.25", "Placer",
        "Dutch Flat", "7.25", "Placer",
        "Emigrant Gap", "7.25", "Placer",
        "Foresthill", "7.25", "Placer",
        "Gold Run", "7.25", "Placer",
        "Granite Bay", "7.25", "Placer",
        "Homewood", "7.25", "Placer",
        "Iowa Hill", "7.25", "Placer",
        "Kings Beach", "7.25", "Placer",
        "Lincoln", "7.25", "Placer",
        "Loomis", "7.50", "Placer",
        "Meadow Vista", "7.25", "Placer",
        "Newcastle", "7.25", "Placer",
        "Olympic Valley", "7.25", "Placer",
        "Penryn", "7.25", "Placer",
        "Rocklin", "7.25", "Placer",
        "Roseville", "7.25", "Placer",
        "Sheridan", "7.25", "Placer",
        "Sunset Whitney Ranch", "7.25", "Placer",
        "Tahoe City", "7.25", "Placer",
        "Tahoe Vista", "7.25", "Placer",
        "Tahoma", "7.25", "Placer",
        "Weimar", "7.25", "Placer",
        "Almanor", "7.25", "Plumas",
        "Beckwourth", "7.25", "Plumas",
        "Belden", "7.25", "Plumas",
        "Blairsden", "7.25", "Plumas",
        "Canyondam", "7.25", "Plumas",
        "Chester", "7.25", "Plumas",
        "Chilcoot", "7.25", "Plumas",
        "Clio", "7.25", "Plumas",
        "Crescent Mills", "7.25", "Plumas",
        "Cromberg", "7.25", "Plumas",
        "Graeagle", "7.25", "Plumas",
        "Greenville", "7.25", "Plumas",
        "Keddie", "7.25", "Plumas",
        "La Porte", "7.25", "Plumas",
        "Meadow Valley", "7.25", "Plumas",
        "Peninsula Village", "7.25", "Plumas",
        "Portola", "7.25", "Plumas",
        "Quincy", "7.25", "Plumas",
        "Sloat", "7.25", "Plumas",
        "Spring Garden", "7.25", "Plumas",
        "Storrie", "7.25", "Plumas",
        "Taylorsville", "7.25", "Plumas",
        "Twain", "7.25", "Plumas",
        "Vinton", "7.25", "Plumas",
        "Virgilia", "7.25", "Plumas",
        "Aguanga", "7.75", "Riverside",
        "Alberhill (Lake Elsinore)", "7.75", "Riverside",
        "Anza", "7.75", "Riverside",
        "Arlington (Riverside)", "8.75", "Riverside",
        "Banning", "7.75", "Riverside",
        "Beaumont", "7.75", "Riverside",
        "Bermuda Dunes", "7.75", "Riverside",
        "Blythe", "7.75", "Riverside",
        "Cabazon", "7.75", "Riverside",
        "Calimesa", "7.75", "Riverside",
        "Canyon Lake", "7.75", "Riverside",
        "Cathedral City", "8.75", "Riverside",
        "Cherry Valley", "7.75", "Riverside",
        "Chiriaco Summit", "7.75", "Riverside",
        "Coachella", "8.75", "Riverside",
        "Corona", "7.75", "Riverside",
        "Desert Center", "7.75", "Riverside",
        "Desert Hot Springs", "7.75", "Riverside",
        "Eagle Mountain", "7.75", "Riverside",
        "Eastvale", "7.75", "Riverside",
        "Edgemont (Moreno Valley)", "7.75", "Riverside",
        "Frontera", "7.75", "Riverside",
        "Garnet", "7.75", "Riverside",
        "Gillman Hot Springs", "7.75", "Riverside",
        "Glen Avon", "7.75", "Riverside",
        "Hemet", "8.75", "Riverside",
        "Highgrove", "7.75", "Riverside",
        "Homeland", "7.75", "Riverside",
        "Homestead", "7.75", "Riverside",
        "Idyllwild", "7.75", "Riverside",
        "Indian Wells", "7.75", "Riverside",
        "Indio", "8.75", "Riverside",
        "Jurupa Valley", "7.75", "Riverside",
        "La Quinta", "8.75", "Riverside",
        "Lake Elsinore", "7.75", "Riverside",
        "Lakeview", "7.75", "Riverside",
        "Lost Lake", "7.75", "Riverside",
        "March A.F.B.", "7.75", "Riverside",
        "Mead Valley", "7.75", "Riverside",
        "Meadowbrook", "7.75", "Riverside",
        "Mecca", "7.75", "Riverside",
        "Menifee", "8.75", "Riverside",
        "Midland", "7.75", "Riverside",
        "Mira Loma", "7.75", "Riverside",
        "Moreno Valley", "7.75", "Riverside",
        "Mountain Center", "7.75", "Riverside",
        "Murrieta", "7.75", "Riverside",
        "Norco", "7.75", "Riverside",
        "North Palm Springs", "7.75", "Riverside",
        "North Shore", "7.75", "Riverside",
        "Nuevo", "7.75", "Riverside",
        "Oasis", "7.75", "Riverside",
        "Palm City", "7.75", "Riverside",
        "Palm Desert", "7.75", "Riverside",
        "Palm Springs", "9.25", "Riverside",
        "Pedley", "7.75", "Riverside",
        "Perris", "7.75", "Riverside",
        "Quail Valley (Menifee)", "8.75", "Riverside",
        "Rancho California", "7.75", "Riverside",
        "Rancho Mirage", "7.75", "Riverside",
        "Ripley", "7.75", "Riverside",
        "Riverside", "8.75", "Riverside",
        "Romoland (Menifee)", "8.75", "Riverside",
        "Rubidoux", "7.75", "Riverside",
        "San Jacinto", "7.75", "Riverside",
        "Sky Valley", "7.75", "Riverside",
        "Smoke Tree (Palm Springs)", "9.25", "Riverside",
        "Sun City (Menifee)", "8.75", "Riverside",
        "Sunnymead (Moreno Valley)", "7.75", "Riverside",
        "Temecula", "8.75", "Riverside",
        "Thermal", "7.75", "Riverside",
        "Thousand Palms", "7.75", "Riverside",
        "Whitewater", "7.75", "Riverside",
        "Wildomar", "7.75", "Riverside",
        "Winchester", "7.75", "Riverside",
        "Antelope", "7.75", "Sacramento",
        "Carmichael", "7.75", "Sacramento",
        "Citrus Heights", "7.75", "Sacramento",
        "Courtland", "7.75", "Sacramento",
        "Elk Grove", "7.75", "Sacramento",
        "Elverta", "7.75", "Sacramento",
        "Fair Oaks", "7.75", "Sacramento",
        "Folsom", "7.75", "Sacramento",
        "Freeport", "7.75", "Sacramento",
        "Galt", "8.25", "Sacramento",
        "Gold River", "7.75", "Sacramento",
        "Herald", "7.75", "Sacramento",
        "Hood", "7.75", "Sacramento",
        "Isleton", "8.75", "Sacramento",
        "Locke", "7.75", "Sacramento",
        "Mather ", "7.75", "Sacramento",
        "McClellan", "7.75", "Sacramento",
        "North Highlands", "7.75", "Sacramento",
        "Orangevale", "7.75", "Sacramento",
        "Rancho Cordova ", "8.25", "Sacramento",
        "Rancho Murieta", "7.75", "Sacramento",
        "Represa (Folsom Prison)", "7.75", "Sacramento",
        "Rio Linda", "7.75", "Sacramento",
        "Ryde", "7.75", "Sacramento",
        "Sacramento", "8.25", "Sacramento",
        "Sherman Island", "7.75", "Sacramento",
        "Sloughhouse", "7.75", "Sacramento",
        "Walnut Grove", "7.75", "Sacramento",
        "Wilton", "7.75", "Sacramento",
        "Hollister", "8.25", "San Benito",
        "Idria", "7.25", "San Benito",
        "New Idria", "7.25", "San Benito",
        "Paicines", "7.25", "San Benito",
        "San Benito", "7.25", "San Benito",
        "San Juan Bautista", "8.00", "San Benito",
        "Tres Pinos", "7.25", "San Benito",
        "Adelanto", "7.75", "San Bernardino",
        "Alta Loma (Rancho Cucamonga)", "7.75", "San Bernardino",
        "Amboy", "7.75", "San Bernardino",
        "Angelus Oaks", "7.75", "San Bernardino",
        "Apple Valley", "7.75", "San Bernardino",
        "Argus", "7.75", "San Bernardino",
        "Arrowbear Lake", "7.75", "San Bernardino",
        "Arrowhead Highlands", "7.75", "San Bernardino",
        "Baker", "7.75", "San Bernardino",
        "Barstow", "7.75", "San Bernardino",
        "Base Line", "7.75", "San Bernardino",
        "Big Bear City", "7.75", "San Bernardino",
        "Big Bear Lake", "7.75", "San Bernardino",
        "Big River", "7.75", "San Bernardino",
        "Bloomington", "7.75", "San Bernardino",
        "Blue Jay", "7.75", "San Bernardino",
        "Bryn Mawr", "7.75", "San Bernardino",
        "Cadiz", "7.75", "San Bernardino",
        "Cedar Glen", "7.75", "San Bernardino",
        "Cedarpines Park", "7.75", "San Bernardino",
        "Chino Hills", "7.75", "San Bernardino",
        "Chino", "7.75", "San Bernardino",
        "Cima", "7.75", "San Bernardino",
        "Colton", "7.75", "San Bernardino",
        "Crest Park", "7.75", "San Bernardino",
        "Crestline", "7.75", "San Bernardino",
        "Cross Roads", "7.75", "San Bernardino",
        "Cucamonga (Rancho Cucamonga)", "7.75", "San Bernardino",
        "Daggett", "7.75", "San Bernardino",
        "Del Rosa", "7.75", "San Bernardino",
        "Earp", "7.75", "San Bernardino",
        "East Highlands (Highland)", "7.75", "San Bernardino",
        "Eastside", "7.75", "San Bernardino",
        "Essex", "7.75", "San Bernardino",
        "Etiwanda (Rancho Cucamonga)", "7.75", "San Bernardino",
        "Fawnskin", "7.75", "San Bernardino",
        "Fenner", "7.75", "San Bernardino",
        "Fontana", "7.75", "San Bernardino",
        "Forest Falls", "7.75", "San Bernardino",
        "Fort Irwin", "7.75", "San Bernardino",
        "George A.F.B.", "7.75", "San Bernardino",
        "Grand Terrace", "7.75", "San Bernardino",
        "Green Valley Lake", "7.75", "San Bernardino",
        "Guasti (Ontario)", "7.75", "San Bernardino",
        "Havasu Lake", "7.75", "San Bernardino",
        "Helendale", "7.75", "San Bernardino",
        "Hesperia", "7.75", "San Bernardino",
        "Highland", "7.75", "San Bernardino",
        "Hinkley", "7.75", "San Bernardino",
        "Ivanpah", "7.75", "San Bernardino",
        "Joshua Tree", "7.75", "San Bernardino",
        "Kelso", "7.75", "San Bernardino",
        "Lake Arrowhead", "7.75", "San Bernardino",
        "Landers", "7.75", "San Bernardino",
        "Lenwood", "7.75", "San Bernardino",
        "Loma Linda", "7.75", "San Bernardino",
        "Los Serranos (Chino Hills)", "7.75", "San Bernardino",
        "Lucerne Valley", "7.75", "San Bernardino",
        "Ludlow", "7.75", "San Bernardino",
        "Lytle Creek", "7.75", "San Bernardino",
        "Marine Corps (Twentynine Palms)", "7.75", "San Bernardino",
        "Mentone", "7.75", "San Bernardino",
        "Montclair", "8.00", "San Bernardino",
        "Moonridge", "7.75", "San Bernardino",
        "Morongo Valley", "7.75", "San Bernardino",
        "Mountain Pass", "7.75", "San Bernardino",
        "Mt. Baldy", "7.75", "San Bernardino",
        "Muscoy", "7.75", "San Bernardino",
        "Needles", "7.75", "San Bernardino",
        "Newberry", "7.75", "San Bernardino",
        "Newberry Springs", "7.75", "San Bernardino",
        "Nipton", "7.75", "San Bernardino",
        "Norton A.F.B. (San Bernardino)", "8.00", "San Bernardino",
        "Ontario", "7.75", "San Bernardino",
        "Oro Grande", "7.75", "San Bernardino",
        "Parker Dam", "7.75", "San Bernardino",
        "Patton", "7.75", "San Bernardino",
        "Phelan", "7.75", "San Bernardino",
        "Pinon Hills", "7.75", "San Bernardino",
        "Pioneertown", "7.75", "San Bernardino",
        "Rancho Cucamonga", "7.75", "San Bernardino",
        "Red Mountain", "7.75", "San Bernardino",
        "Redlands", "7.75", "San Bernardino",
        "Rialto", "7.75", "San Bernardino",
        "Rimforest", "7.75", "San Bernardino",
        "Running Springs", "7.75", "San Bernardino",
        "San Bernardino", "8.00", "San Bernardino",
        "Skyforest", "7.75", "San Bernardino",
        "Smoke Tree (Twentynine Palms)", "7.75", "San Bernardino",
        "Sugarloaf", "7.75", "San Bernardino",
        "Summit", "7.75", "San Bernardino",
        "Trona", "7.75", "San Bernardino",
        "Twentynine Palms", "7.75", "San Bernardino",
        "Twin Peaks", "7.75", "San Bernardino",
        "Upland", "7.75", "San Bernardino",
        "Victorville", "7.75", "San Bernardino",
        "Vidal", "7.75", "San Bernardino",
        "Westend", "7.75", "San Bernardino",
        "Wrightwood", "7.75", "San Bernardino",
        "Yermo", "7.75", "San Bernardino",
        "Yucaipa", "7.75", "San Bernardino",
        "Yucca Valley", "8.75", "San Bernardino",
        "Agua Caliente Springs", "7.75", "San Diego",
        "Alpine", "7.75", "San Diego",
        "Balboa Park (San Diego)", "7.75", "San Diego",
        "Bonita", "7.75", "San Diego",
        "Bonsall", "7.75", "San Diego",
        "Borrego Springs", "7.75", "San Diego",
        "Bostonia", "7.75", "San Diego",
        "Boulevard", "7.75", "San Diego",
        "Camp Pendleton", "7.75", "San Diego",
        "Campo", "7.75", "San Diego",
        "Cardiff By The Sea (Encinitas)", "7.75", "San Diego",
        "Carlsbad", "7.75", "San Diego",
        "Chula Vista", "8.75", "San Diego",
        "College Grove Center", "7.75", "San Diego",
        "Coronado", "7.75", "San Diego",
        "Crest", "7.75", "San Diego",
        "Del Mar", "8.75", "San Diego",
        "Descanso", "7.75", "San Diego",
        "Dulzura", "7.75", "San Diego",
        "El Cajon", "8.25", "San Diego",
        "Encinitas", "7.75", "San Diego",
        "Escondido", "7.75", "San Diego",
        "Fallbrook", "7.75", "San Diego",
        "Fallbrook Junction", "7.75", "San Diego",
        "Flinn Springs", "7.75", "San Diego",
        "Guatay", "7.75", "San Diego",
        "Harbison Canyon", "7.75", "San Diego",
        "Hillcrest (San Diego)", "7.75", "San Diego",
        "Imperial Beach", "7.75", "San Diego",
        "Jacumba", "7.75", "San Diego",
        "Jamacha", "7.75", "San Diego",
        "Jamul", "7.75", "San Diego",
        "Johnstown", "7.75", "San Diego",
        "Julian", "7.75", "San Diego",
        "La Jolla (San Diego)", "7.75", "San Diego",
        "La Mesa", "8.50", "San Diego",
        "Lake San Marcos", "7.75", "San Diego",
        "Lakeside", "7.75", "San Diego",
        "Lemon Grove", "7.75", "San Diego",
        "Leucadia (Encinitas)", "7.75", "San Diego",
        "Lincoln Acres", "7.75", "San Diego",
        "Miramar (San Diego)", "7.75", "San Diego",
        "Mount Laguna", "7.75", "San Diego",
        "National City", "8.75", "San Diego",
        "Naval (San Diego)", "7.75", "San Diego",
        "Naval Air Station (Coronado)", "7.75", "San Diego",
        "Naval Hospital (San Diego)", "7.75", "San Diego",
        "Naval Training Center (San Diego)", "7.75", "San Diego",
        "Oceanside", "7.75", "San Diego",
        "Ocotillo Wells", "7.75", "San Diego",
        "Olivenhain (Encinitas)", "7.75", "San Diego",
        "Otay (Chula Vista)", "8.25", "San Diego",
        "Pala", "7.75", "San Diego",
        "Palm City (San Diego)", "7.75", "San Diego",
        "Palomar Mountain", "7.75", "San Diego",
        "Pauma Valley", "7.75", "San Diego",
        "Pine Valley", "7.75", "San Diego",
        "Potrero", "7.75", "San Diego",
        "Poway", "7.75", "San Diego",
        "Rainbow", "7.75", "San Diego",
        "Ramona", "7.75", "San Diego",
        "Ranchita", "7.75", "San Diego",
        "Rancho Bernardo (San Diego)", "7.75", "San Diego",
        "Rancho Santa Fe", "7.75", "San Diego",
        "San Carlos (San Diego)", "7.75", "San Diego",
        "San Diego", "7.75", "San Diego",
        "San Luis Rey (Oceanside)", "7.75", "San Diego",
        "San Marcos", "7.75", "San Diego",
        "San Ysidro (San Diego)", "7.75", "San Diego",
        "Santa Ysabel", "7.75", "San Diego",
        "Santee", "7.75", "San Diego",
        "Solana Beach", "7.75", "San Diego",
        "Spring Valley", "7.75", "San Diego",
        "Sunnyside", "7.75", "San Diego",
        "Tecate", "7.75", "San Diego",
        "Tierra Del Sol", "7.75", "San Diego",
        "Tierrasanta (San Diego)", "7.75", "San Diego",
        "Valley Center", "7.75", "San Diego",
        "Vista", "8.25", "San Diego",
        "Warner Springs", "7.75", "San Diego",
        "Presidio (San Francisco)", "8.50", "San Francisco",
        "San Francisco", "8.50", "San Francisco",
        "Acampo", "7.75", "San Joaquin",
        "Banta", "7.75", "San Joaquin",
        "Clements", "7.75", "San Joaquin",
        "Escalon", "7.75", "San Joaquin",
        "Farmington", "7.75", "San Joaquin",
        "French Camp", "7.75", "San Joaquin",
        "Holt", "7.75", "San Joaquin",
        "Lathrop", "8.75", "San Joaquin",
        "Lincoln Village", "7.75", "San Joaquin",
        "Linden", "7.75", "San Joaquin",
        "Lockeford", "7.75", "San Joaquin",
        "Lodi", "7.75", "San Joaquin",
        "Manteca", "8.25", "San Joaquin",
        "Ripon", "7.75", "San Joaquin",
        "Sharpe Army Depot", "7.75", "San Joaquin",
        "Stockton", "9.00", "San Joaquin",
        "Thornton", "7.75", "San Joaquin",
        "Tracy", "8.25", "San Joaquin",
        "Vernalis", "7.75", "San Joaquin",
        "Victor", "7.75", "San Joaquin",
        "Woodbridge", "7.75", "San Joaquin",
        "Adelaida", "7.25", "San Luis Obispo",
        "Arroyo Grande", "7.75", "San Luis Obispo",
        "Atascadero", "7.75", "San Luis Obispo",
        "Avila Beach", "7.25", "San Luis Obispo",
        "Baywood Park", "7.25", "San Luis Obispo",
        "California Valley", "7.25", "San Luis Obispo",
        "Cambria", "7.25", "San Luis Obispo",
        "Cayucos", "7.25", "San Luis Obispo",
        "Cholame", "7.25", "San Luis Obispo",
        "Creston", "7.25", "San Luis Obispo",
        "Del Mar Heights (Morro Bay)", "7.75", "San Luis Obispo",
        "Grover Beach", "7.75", "San Luis Obispo",
        "Halcyon", "7.25", "San Luis Obispo",
        "Harmony", "7.25", "San Luis Obispo",
        "Los Osos", "7.25", "San Luis Obispo",
        "Los Padres", "7.25", "San Luis Obispo",
        "Morro Bay", "7.75", "San Luis Obispo",
        "Morro Plaza", "7.25", "San Luis Obispo",
        "Nipomo", "7.25", "San Luis Obispo",
        "Oceano", "7.25", "San Luis Obispo",
        "Paso Robles", "7.75", "San Luis Obispo",
        "Pismo Beach", "7.75", "San Luis Obispo",
        "San Luis Obispo", "7.75", "San Luis Obispo",
        "San Miguel", "7.25", "San Luis Obispo",
        "San Simeon", "7.25", "San Luis Obispo",
        "Santa Margarita", "7.25", "San Luis Obispo",
        "Shandon", "7.25", "San Luis Obispo",
        "Shell Beach (Pismo Beach)", "7.75", "San Luis Obispo",
        "Templeton", "7.25", "San Luis Obispo",
        "Atherton", "8.75", "San Mateo",
        "Belmont", "9.25", "San Mateo",
        "Brisbane", "8.75", "San Mateo",
        "Burlingame", "9.00", "San Mateo",
        "Colma", "8.75", "San Mateo",
        "Daly City", "8.75", "San Mateo",
        "East Palo Alto", "9.25", "San Mateo",
        "El Granada", "8.75", "San Mateo",
        "Emerald Hills (Redwood City)", "8.75", "San Mateo",
        "Foster City", "8.75", "San Mateo",
        "Half Moon Bay", "8.75", "San Mateo",
        "Hillsborough", "8.75", "San Mateo",
        "Hillsdale (San Mateo)", "9.00", "San Mateo",
        "La Honda", "8.75", "San Mateo",
        "Ladera", "8.75", "San Mateo",
        "Loma Mar", "8.75", "San Mateo",
        "Marsh Manor", "8.75", "San Mateo",
        "Menlo Park", "8.75", "San Mateo",
        "Millbrae", "8.75", "San Mateo",
        "Montara", "8.75", "San Mateo",
        "Moss Beach", "8.75", "San Mateo",
        "Pacifica", "8.75", "San Mateo",
        "Pescadero", "8.75", "San Mateo",
        "Portola Valley", "8.75", "San Mateo",
        "Redwood City", "8.75", "San Mateo",
        "San Bruno", "8.75", "San Mateo",
        "San Carlos", "8.75", "San Mateo",
        "San Gregorio", "8.75", "San Mateo",
        "San Mateo", "9.00", "San Mateo",
        "South San Francisco", "9.25", "San Mateo",
        "Woodside", "8.75", "San Mateo",
        "Ballard", "7.75", "Santa Barbara",
        "Betteravia", "7.75", "Santa Barbara",
        "Buellton", "7.75", "Santa Barbara",
        "Carpinteria", "7.75", "Santa Barbara",
        "Casmalia", "7.75", "Santa Barbara",
        "Cuyama", "7.75", "Santa Barbara",
        "Garey", "7.75", "Santa Barbara",
        "Gaviota", "7.75", "Santa Barbara",
        "Goleta", "7.75", "Santa Barbara",
        "Guadalupe", "8.00", "Santa Barbara",
        "Isla Vista", "7.75", "Santa Barbara",
        "Lompoc", "7.75", "Santa Barbara",
        "Los Alamos", "7.75", "Santa Barbara",
        "Los Olivos", "7.75", "Santa Barbara",
        "Montecito", "7.75", "Santa Barbara",
        "New Cuyama", "7.75", "Santa Barbara",
        "Orcutt", "7.75", "Santa Barbara",
        "Refugio Beach", "7.75", "Santa Barbara",
        "Santa Barbara (U.C. Santa Barbara campus rate is 7.75%)",
            "8.75", "Santa Barbara",
        "Santa Maria", "8.00", "Santa Barbara",
        "Santa Ynez", "7.75", "Santa Barbara",
        "Sisquoc", "7.75", "Santa Barbara",
        "Solvang", "7.75", "Santa Barbara",
        "Summerland", "7.75", "Santa Barbara",
        "University", "7.75", "Santa Barbara",
        "Vandenberg A.F.B", "7.75", "Santa Barbara",
        "Ventucopa", "7.75", "Santa Barbara",
        "Almaden Valley", "9.00", "Santa Clara",
        "Alviso (San Jose)", "9.25", "Santa Clara",
        "Blossom Hill", "9.00", "Santa Clara",
        "Blossom Valley", "9.00", "Santa Clara",
        "Cambrian Park", "9.00", "Santa Clara",
        "Campbell", "9.25", "Santa Clara",
        "Coyote", "9.00", "Santa Clara",
        "Cupertino", "9.00", "Santa Clara",
        "Gilroy", "9.00", "Santa Clara",
        "Holy City", "9.00", "Santa Clara",
        "Lorre Estates", "9.00", "Santa Clara",
        "Los Altos Hills", "9.00", "Santa Clara",
        "Los Altos", "9.00", "Santa Clara",
        "Los Gatos", "9.00", "Santa Clara",
        "Milpitas", "9.00", "Santa Clara",
        "Moffett Field", "9.00", "Santa Clara",
        "Monta Vista", "9.00", "Santa Clara",
        "Monte Sereno", "9.00", "Santa Clara",
        "Morgan Hill", "9.00", "Santa Clara",
        "Mount Hamilton", "9.00", "Santa Clara",
        "Mountain View", "9.00", "Santa Clara",
        "New Almaden", "9.00", "Santa Clara",
        "Palo Alto", "9.00", "Santa Clara",
        "Permanente", "9.00", "Santa Clara",
        "Redwood Estates", "9.00", "Santa Clara",
        "San Jose", "9.25", "Santa Clara",
        "San Martin", "9.00", "Santa Clara",
        "San Tomas", "9.00", "Santa Clara",
        "Santa Clara", "9.00", "Santa Clara",
        "Saratoga", "9.00", "Santa Clara",
        "Stanford", "9.00", "Santa Clara",
        "Sunnyvale", "9.00", "Santa Clara",
        "Valley Fair", "9.00", "Santa Clara",
        "Aptos", "8.50", "Santa Cruz",
        "Ben Lomond", "8.50", "Santa Cruz",
        "Big Basin", "8.50", "Santa Cruz",
        "Bonny Doon", "8.50", "Santa Cruz",
        "Boulder Creek", "8.50", "Santa Cruz",
        "Brookdale", "8.50", "Santa Cruz",
        "Capitola", "9.00", "Santa Cruz",
        "Corralitos", "8.50", "Santa Cruz",
        "Davenport", "8.50", "Santa Cruz",
        "Felton", "8.50", "Santa Cruz",
        "Freedom", "8.50", "Santa Cruz",
        "Freedom (Watsonville)", "9.25", "Santa Cruz",
        "La Selva Beach", "8.50", "Santa Cruz",
        "Live Oak ", "8.50", "Santa Cruz",
        "Lockheed", "8.50", "Santa Cruz",
        "Monterey Bay Academy", "8.50", "Santa Cruz",
        "Mount Hermon", "8.50", "Santa Cruz",
        "Opal Cliffs", "8.50", "Santa Cruz",
        "Rio Del Mar", "8.50", "Santa Cruz",
        "Santa Cruz", "9.25", "Santa Cruz",
        "Scotts Valley", "9.00", "Santa Cruz",
        "Seabright (Santa Cruz)", "9.00", "Santa Cruz",
        "Soquel", "8.50", "Santa Cruz",
        "Watsonville", "9.25", "Santa Cruz",
        "Anderson", "7.75", "Shasta",
        "Bella Vista", "7.25", "Shasta",
        "Big Bend", "7.25", "Shasta",
        "Burney", "7.25", "Shasta",
        "Cassel", "7.25", "Shasta",
        "Castella", "7.25", "Shasta",
        "Central Valley", "7.25", "Shasta",
        "Cottonwood", "7.25", "Shasta",
        "Enterprise", "7.25", "Shasta",
        "Fall River Mills", "7.25", "Shasta",
        "French Gulch", "7.25", "Shasta",
        "Glenburn", "7.25", "Shasta",
        "Hat Creek", "7.25", "Shasta",
        "Igo", "7.25", "Shasta",
        "Keswick", "7.25", "Shasta",
        "Lakehead", "7.25", "Shasta",
        "Manzanita Lake", "7.25", "Shasta",
        "McArthur", "7.25", "Shasta",
        "Millville", "7.25", "Shasta",
        "Montgomery Creek", "7.25", "Shasta",
        "Oak Run", "7.25", "Shasta",
        "O'Brien", "7.25", "Shasta",
        "Old Station", "7.25", "Shasta",
        "Olinda", "7.25", "Shasta",
        "Ono", "7.25", "Shasta",
        "Palo Cedro", "7.25", "Shasta",
        "Platina", "7.25", "Shasta",
        "Project City", "7.25", "Shasta",
        "Redding", "7.25", "Shasta",
        "Round Mountain", "7.25", "Shasta",
        "Shasta", "7.25", "Shasta",
        "Shasta Lake", "7.25", "Shasta",
        "Shingletown", "7.25", "Shasta",
        "Summit City", "7.25", "Shasta",
        "Whiskeytown", "7.25", "Shasta",
        "Whitmore", "7.25", "Shasta",
        "Wildwood", "7.25", "Shasta",
        "Alleghany", "7.25", "Sierra",
        "Calpine", "7.25", "Sierra",
        "Downieville", "7.25", "Sierra",
        "Goodyears Bar", "7.25", "Sierra",
        "Loyalton", "7.25", "Sierra",
        "Sattley", "7.25", "Sierra",
        "Sierra City", "7.25", "Sierra",
        "Sierraville", "7.25", "Sierra",
        "Callahan", "7.25", "Siskiyou",
        "Cecilville", "7.25", "Siskiyou",
        "Clear Creek", "7.25", "Siskiyou",
        "Dorris", "7.25", "Siskiyou",
        "Dunsmuir", "7.75", "Siskiyou",
        "Edgewood", "7.25", "Siskiyou",
        "Etna", "7.25", "Siskiyou",
        "Forks of Salmon", "7.25", "Siskiyou",
        "Fort Jones", "7.25", "Siskiyou",
        "Gazelle", "7.25", "Siskiyou",
        "Greenview", "7.25", "Siskiyou",
        "Grenada", "7.25", "Siskiyou",
        "Happy Camp", "7.25", "Siskiyou",
        "Hilt", "7.25", "Siskiyou",
        "Hornbrook", "7.25", "Siskiyou",
        "Horse Creek", "7.25", "Siskiyou",
        "Kinyon", "7.25", "Siskiyou",
        "Klamath River", "7.25", "Siskiyou",
        "Lake Shastina", "7.25", "Siskiyou",
        "Macdoel", "7.25", "Siskiyou",
        "McCloud", "7.25", "Siskiyou",
        "Montague", "7.25", "Siskiyou",
        "Mount Hebron", "7.25", "Siskiyou",
        "Mount Shasta", "7.50", "Siskiyou",
        "Pondosa", "7.25", "Siskiyou",
        "Sawyers Bar", "7.25", "Siskiyou",
        "Scott Bar", "7.25", "Siskiyou",
        "Seiad Valley", "7.25", "Siskiyou",
        "Somes Bar", "7.25", "Siskiyou",
        "Tulelake", "7.25", "Siskiyou",
        "Weed", "7.50", "Siskiyou",
        "Yreka", "7.75", "Siskiyou",
        "Benicia", "8.38", "Solano",
        "Birds Landing", "7.38", "Solano",
        "Dairy Farm", "7.38", "Solano",
        "Dixon", "7.38", "Solano",
        "Elmira", "7.38", "Solano",
        "Fairfield", "8.38", "Solano",
        "Larwin Plaza", "7.38", "Solano",
        "Liberty Farms", "7.38", "Solano",
        "Mare Island (Vallejo)", "8.38", "Solano",
        "Rio Vista", "8.13", "Solano",
        "Suisun City", "8.38", "Solano",
        "Travis A.F.B. (Fairfield)", "8.38", "Solano",
        "Vacaville", "8.13", "Solano",
        "Vallejo", "8.38", "Solano",
        "Agua Caliente", "8.13", "Sonoma",
        "Annapolis", "8.13", "Sonoma",
        "Asti", "8.13", "Sonoma",
        "Bodega", "8.13", "Sonoma",
        "Bodega Bay", "8.13", "Sonoma",
        "Boyes Hot Springs", "8.13", "Sonoma",
        "Camp Meeker", "8.13", "Sonoma",
        "Cazadero", "8.13", "Sonoma",
        "Cloverdale", "8.13", "Sonoma",
        "Cotati", "9.13", "Sonoma",
        "Duncans Mills", "8.13", "Sonoma",
        "El Verano", "8.13", "Sonoma",
        "Eldridge", "8.13", "Sonoma",
        "Forestville", "8.13", "Sonoma",
        "Freestone", "8.13", "Sonoma",
        "Fulton", "8.13", "Sonoma",
        "Geyserville", "8.13", "Sonoma",
        "Glen Ellen", "8.13", "Sonoma",
        "Graton", "8.13", "Sonoma",
        "Guerneville", "8.13", "Sonoma",
        "Healdsburg", "8.63", "Sonoma",
        "Jenner", "8.13", "Sonoma",
        "Kenwood", "8.13", "Sonoma",
        "Korbel", "8.13", "Sonoma",
        "Larkfield", "8.13", "Sonoma",
        "Monte Rio", "8.13", "Sonoma",
        "Occidental", "8.13", "Sonoma",
        "Penngrove", "8.13", "Sonoma",
        "Petaluma", "8.13", "Sonoma",
        "Rio Nido", "8.13", "Sonoma",
        "Rohnert Park", "8.63", "Sonoma",
        "Roseland", "8.13", "Sonoma",
        "Santa Rosa", "8.63", "Sonoma",
        "Sea Ranch", "8.13", "Sonoma",
        "Sebastopol", "8.88", "Sonoma",
        "Sonoma", "8.63", "Sonoma",
        "Stewarts Point", "8.13", "Sonoma",
        "Two Rock Coast Guard Station", "8.13", "Sonoma",
        "Valley Ford", "8.13", "Sonoma",
        "Villa Grande", "8.13", "Sonoma",
        "Vineburg", "8.13", "Sonoma",
        "Windsor", "8.13", "Sonoma",
        "Ceres", "8.38", "Stanislaus",
        "Crows Landing", "7.88", "Stanislaus",
        "Denair", "7.88", "Stanislaus",
        "El Viejo", "7.88", "Stanislaus",
        "Empire", "7.88", "Stanislaus",
        "Hickman", "7.88", "Stanislaus",
        "Hughson", "7.88", "Stanislaus",
        "Keyes", "7.88", "Stanislaus",
        "Knights Ferry", "7.88", "Stanislaus",
        "La Grange", "7.88", "Stanislaus",
        "Modesto", "7.88", "Stanislaus",
        "Newman", "7.88", "Stanislaus",
        "Oakdale", "8.38", "Stanislaus",
        "Patterson", "7.88", "Stanislaus",
        "Riverbank", "7.88", "Stanislaus",
        "Salida", "7.88", "Stanislaus",
        "Turlock", "7.88", "Stanislaus",
        "Valley Home", "7.88", "Stanislaus",
        "Waterford", "7.88", "Stanislaus",
        "Westley", "7.88", "Stanislaus",
        "Westside", "7.88", "Stanislaus",
        "East Nicolaus", "7.25", "Sutter",
        "Live Oak", "7.25", "Sutter",
        "Meridian", "7.25", "Sutter",
        "Nicolaus", "7.25", "Sutter",
        "Pleasant Grove", "7.25", "Sutter",
        "Rio Oso", "7.25", "Sutter",
        "Robbins", "7.25", "Sutter",
        "Sutter", "7.25", "Sutter",
        "Trowbridge", "7.25", "Sutter",
        "Yuba City", "7.25", "Sutter",
        "Corning", "7.75", "Tehama",
        "Flournoy", "7.25", "Tehama",
        "Gerber", "7.25", "Tehama",
        "Los Molinos", "7.25", "Tehama",
        "Manton", "7.25", "Tehama",
        "Mill Creek", "7.25", "Tehama",
        "Mineral", "7.25", "Tehama",
        "Paskenta", "7.25", "Tehama",
        "Paynes Creek", "7.25", "Tehama",
        "Proberta", "7.25", "Tehama",
        "Red Bluff", "7.50", "Tehama",
        "Richfield", "7.25", "Tehama",
        "Tehama", "7.25", "Tehama",
        "Vina", "7.25", "Tehama",
        "Big Bar", "7.25", "Trinity",
        "Burnt Ranch", "7.25", "Trinity",
        "Denny", "7.25", "Trinity",
        "Douglas City", "7.25", "Trinity",
        "Forest Glen", "7.25", "Trinity",
        "Hayfork", "7.25", "Trinity",
        "Helena", "7.25", "Trinity",
        "Hyampom", "7.25", "Trinity",
        "Island Mountain", "7.25", "Trinity",
        "Junction City", "7.25", "Trinity",
        "Lewiston", "7.25", "Trinity",
        "Mad River", "7.25", "Trinity",
        "Ruth", "7.25", "Trinity",
        "Salyer", "7.25", "Trinity",
        "Trinity Center", "7.25", "Trinity",
        "Weaverville", "7.25", "Trinity",
        "Zenia", "7.25", "Trinity",
        "Alpaugh", "7.75", "Tulare",
        "Badger", "7.75", "Tulare",
        "California Hot Springs", "7.75", "Tulare",
        "Camp Kaweah", "7.75", "Tulare",
        "Camp Nelson", "7.75", "Tulare",
        "Cutler", "7.75", "Tulare",
        "Dinuba", "8.50", "Tulare",
        "Ducor", "7.75", "Tulare",
        "Earlimart", "7.75", "Tulare",
        "East Porterville", "7.75", "Tulare",
        "Exeter", "7.75", "Tulare",
        "Farmersville", "8.75", "Tulare",
        "Giant Forest", "7.75", "Tulare",
        "Goshen", "7.75", "Tulare",
        "Ivanhoe", "7.75", "Tulare",
        "Johnsondale", "7.75", "Tulare",
        "Kaweah", "7.75", "Tulare",
        "Kings Canyon National Park", "7.75", "Tulare",
        "Lemoncove", "7.75", "Tulare",
        "Lindsay", "8.75", "Tulare",
        "Linnell", "7.75", "Tulare",
        "London", "7.75", "Tulare",
        "Mineral King", "7.75", "Tulare",
        "Mooney", "7.75", "Tulare",
        "Orosi", "7.75", "Tulare",
        "Pixley", "7.75", "Tulare",
        "Plainview", "7.75", "Tulare",
        "Poplar", "7.75", "Tulare",
        "Porterville", "8.25", "Tulare",
        "Posey", "7.75", "Tulare",
        "Richgrove", "7.75", "Tulare",
        "Sequoia National Park", "7.75", "Tulare",
        "Springville", "7.75", "Tulare",
        "Strathmore", "7.75", "Tulare",
        "Sultana", "7.75", "Tulare",
        "Tagus Ranch", "7.75", "Tulare",
        "Terra Bella", "7.75", "Tulare",
        "Three Rivers", "7.75", "Tulare",
        "Tipton", "7.75", "Tulare",
        "Town Center", "7.75", "Tulare",
        "Traver", "7.75", "Tulare",
        "Tulare", "8.25", "Tulare",
        "Visalia", "8.50", "Tulare",
        "Waukena", "7.75", "Tulare",
        "Woodlake", "8.75", "Tulare",
        "Woodville", "7.75", "Tulare",
        "Yettem", "7.75", "Tulare",
        "Big Oak Flat", "7.25", "Tuolumne",
        "Chinese Camp", "7.25", "Tuolumne",
        "Columbia", "7.25", "Tuolumne",
        "Dardanelle", "7.25", "Tuolumne",
        "Groveland", "7.25", "Tuolumne",
        "Jamestown", "7.25", "Tuolumne",
        "Long Barn", "7.25", "Tuolumne",
        "Mather", "7.25", "Tuolumne",
        "Mi-Wuk Village", "7.25", "Tuolumne",
        "Moccasin", "7.25", "Tuolumne",
        "Pinecrest", "7.25", "Tuolumne",
        "Sonora", "7.75", "Tuolumne",
        "Soulsbyville", "7.25", "Tuolumne",
        "Standard", "7.25", "Tuolumne",
        "Stanislaus", "7.25", "Tuolumne",
        "Strawberry", "7.25", "Tuolumne",
        "Tuolumne", "7.25", "Tuolumne",
        "Twain Harte", "7.25", "Tuolumne",
        "Camarillo", "7.25", "Ventura",
        "Casitas Springs", "7.25", "Ventura",
        "Fillmore", "7.25", "Ventura",
        "Lake Sherwood", "7.25", "Ventura",
        "Meiners Oaks", "7.25", "Ventura",
        "Montalvo (Ventura)", "7.75", "Ventura",
        "Moorpark", "7.25", "Ventura",
        "Naval (Port Hueneme)", "7.75", "Ventura",
        "Newbury Park (Thousand Oaks)", "7.25", "Ventura",
        "Nyeland Acres", "7.25", "Ventura",
        "Oak Park", "7.25", "Ventura",
        "Oak View", "7.25", "Ventura",
        "Ojai", "7.25", "Ventura",
        "Oxnard", "7.75", "Ventura",
        "Piru", "7.25", "Ventura",
        "Point Mugu", "7.25", "Ventura",
        "Port Hueneme", "7.75", "Ventura",
        "Santa Paula", "8.25", "Ventura",
        "Santa Rosa Valley", "7.25", "Ventura",
        "Saticoy", "7.25", "Ventura",
        "Simi Valley", "7.25", "Ventura",
        "Somis", "7.25", "Ventura",
        "Thousand Oaks", "7.25", "Ventura",
        "Ventura", "7.75", "Ventura",
        "Westlake Village (Thousand Oaks)", "7.25", "Ventura",
        "Broderick (West Sacramento)", "8.00", "Yolo",
        "Brooks", "7.25", "Yolo",
        "Bryte (West Sacramento)", "8.00", "Yolo",
        "Capay", "7.25", "Yolo",
        "Clarksburg", "7.25", "Yolo",
        "Davis (U.C. Davis campus rate is 7.25%)", "8.25", "Yolo",
        "Dunnigan", "7.25", "Yolo",
        "El Macero", "7.25", "Yolo",
        "Esparto", "7.25", "Yolo",
        "Guinda", "7.25", "Yolo",
        "Knights Landing", "7.25", "Yolo",
        "Madison", "7.25", "Yolo",
        "Rumsey", "7.25", "Yolo",
        "West Sacramento", "8.00", "Yolo",
        "Winters", "7.25", "Yolo",
        "Woodland", "8.00", "Yolo",
        "Yolo", "7.25", "Yolo",
        "Zamora", "7.25", "Yolo",
        "Beale A.F.B.", "7.25", "Yuba",
        "Browns Valley", "7.25", "Yuba",
        "Brownsville", "7.25", "Yuba",
        "Camp Beale", "7.25", "Yuba",
        "Camptonville", "7.25", "Yuba",
        "Challenge", "7.25", "Yuba",
        "Dobbins", "7.25", "Yuba",
        "Linda", "7.25", "Yuba",
        "Loma Rica", "7.25", "Yuba",
        "Marysville", "8.25", "Yuba",
        "Olivehurst", "7.25", "Yuba",
        "Oregon House", "7.25", "Yuba",
        "Rackerby", "7.25", "Yuba",
        "Smartsville", "7.25", "Yuba",
        "Strawberry Valley", "7.25", "Yuba",
        "Wheatland", "7.75", "Yuba",
        "Woodleaf", "7.25", "Yuba" };
    //TODO: sort the array by city name (for the binary search)
        selectionSort(SalesTax, ROWS);

    choice = Menu();
    while (choice < EXIT)
    {
        firstCity = true;
        switch (choice)
        {
        case CITY:
            cout << "Please enter city name: ";
            getline(cin, city);

            //TODO: binary search for city, return index of found record
            // note: stod() converts a string to a double
            index = binarySearch(SalesTax, ROWS, city);
            if (index >= 0)
            {
                city = SalesTax[index][0]; //testing only
                rate = SalesTax[index][1]; //testing only
                county = SalesTax[index][2]; //testing only
                DisplayRecord(city, stod(rate), county, SHOWHEADINGS);
            }
            else
            {
                cout << "Record not found.";
            }
            break;
        case COUNTY:
            cout << "Please enter county name: ";
            getline(cin, county);
            //TODO: sequential search for ALL matching records return all the fields
            index = sequentialSearch(SalesTax, ROWS, county, countyFound);
            if (index >= 0)
            {
                for (int i = 0; i < ROWS; i++)
                {
                    if (countyFound[i] == true)
                    {
                        city = SalesTax[i][0];
                        rate = SalesTax[i][1];
                        county = SalesTax[i][2];

                        if (firstCity)
                        {
                            DisplayRecord(city, stod(rate), county, SHOWHEADINGS); //first record
                            firstCity = false;
                        }
                        else
                        {
                            DisplayRecord(city, stod(rate), county, NOHEADINGS);
                        }
                    }
                }
            }
            else
            {
                cout << "Record not found.";
            }
            
            break;
        }
        choice = Menu();
    }

    return 0;
}

int Menu()
{
    int choice;
    const int MIN = 1, MAX = 3;

    cout << "\n\nCalifornia Sales Tax Rates\n"
        << "--------------------------\n"
        << "1. By City Name\n"
        << "2. By County\n"
        << "3. Exit\n\n"
        << "Selection: ";

    cin >> choice;
    while (choice < MIN || choice > MAX)
    {
        cout << "Please enter " << MIN << " - " << MAX << " only: ";
        cin >> choice;
    }
    cin.ignore();

    return choice;
}

void DisplayRecord(string city, double rate, string county, bool headings)
{
    if (headings)
    {
        DisplayRecordHeading();
    }
    cout << setw(30) << city
        << fixed << setw(10) << setprecision(3) << rate
        << setw(20) << county << endl;
}

void DisplayRecordHeading()
{
    cout << "\n   City Name                       Tax Rate        County\n"
        "-----------------------------------------------------------\n";
}

void selectionSort(string SalesTax[][3], int size)
{
    int startScan, minIndex;
    string minValue, minValueY, minValueZ;

    for (startScan = 0; startScan < (size - 1); startScan++)
    {
        minIndex = startScan;
        minValue = SalesTax[startScan][0];

        for (int index = startScan + 1; index < size; index++)
        {
            if (SalesTax[index][0] < minValue)
            {
                minValue = SalesTax[index][0];
                minValueY = SalesTax[index][1];
                minValueZ = SalesTax[index][2];
                minIndex = index;
            }
        }
        SalesTax[minIndex][0] = SalesTax[startScan][0];
        SalesTax[minIndex][1] = SalesTax[startScan][1];
        SalesTax[minIndex][2] = SalesTax[startScan][2];
        SalesTax[startScan][0] = minValue;
        SalesTax[startScan][1] = minValueY;
        SalesTax[startScan][2] = minValueZ;
    }
}

int binarySearch(string SalesTax[][3], int size, string city)
{
    int first = 0,
        last = size - 1,
        middle,
        position = -1;
    bool found = false;
    while (found == false && first <= last)
    {
        middle = (first + last) / 2;
        if (SalesTax[middle][0] == city)
        {
            found = true;
            position = middle;
        }
        else if (SalesTax[middle][0] > city)
        {
            last = middle - 1;
        }
        else
        {
            first = middle + 1;
        }
    }
    return position;
}

int sequentialSearch(string salesTax[][3], int size,
    string county, bool countyFound[])
{
    int index = 0, position = -1;

    for (int i = 0; i < size; i++)
    {
        countyFound[i] = false;
    }

    while (countyFound[index] == false && index < size)
    {
        if (salesTax[index][2] == county)
        {
            countyFound[index] = true;
            position = index;
        }
        index++;
    }
    return position;
}
